baseURL: 'https://api.covidbahamas.app/'
languageCode: en-uk
title: COVID-19 API Bahamas

upload_dir: static/uploads
public_path: /uploads

disableKinds:
  - taxonomy
  - taxonomyTerm
  - categories

outputs:
  page:
    - HTML
    - json
    # - CSV
  section:
    - HTML
    - json
    # - CSV
  home:
    - HTML

# uglyURLs: true

# outputFormats:
#   html:
#     noUgly: true
#   json:
#     path: api

# git clone --single-branch -b hugo-forum-topic-23945 https://github.com/jmooring/hugo-testing hugo-forum-topic-23945
# cd hugo-forum-topic-23945
# hugo && tree public

# paginate: 2

markup:
  goldmark:
    renderer:
      unsafe: true

